version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: shopmon-cli
    binary: shopmon-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    dir: .

archives:
  - builds:
      - shopmon-cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: friendsofshopware
    name: shopmon-cli
